### ISSUE TITLE
User's Guide:Application Development:Docker image links are broken

### ISSUE THREAD

**Issue by nickahoy** [zalando-stups/documentation#109]
- Describe how to use `pierone` to browse for and choose an appropriate base image
- Document who is responsible for maintaining base images & links to the dockerfiles used to generate them

**Comment by hjacobs** [comment]
Thanks for reporting this issue --- I replaced the links to Docker Hub with a link to the existing "base images" section: http://docs.stups.io/en/latest/appendix/docker-base-images.html#docker-base-images
