### ISSUE TITLE
ElasticLoadBalancer can accept multiple Loadbalancers

### ISSUE THREAD

**Issue by arjunrn** [zalando-stups/documentation#52]
The **ElasticLoadBalancer** for the _Senza::TaupageAutoScalingGroup_ component can take an array as parameter when more than one load balancer is to be attached to the Auto-Scaling group. But the documentation does not mention this feature. I am currently using this feature to have two LBs for an ASG. One internal facing and the other internet facing. This is required because the internal facing LB balances a TCP connection which is not secured, i.e. it is done to be STUPs rules compliant. Should I submit a PR with to update the documentation?

**Comment by hjacobs** [comment]
@arjunrn sure, PRs are welcome :smile:

**Comment by hjacobs** [comment]
@arjunrn you are right, I now documented here: https://docs.stups.io/en/latest/components/senza.html#senza-taupageautoscalinggroup
