### ISSUE TITLE
"push" doesn't work for docker 1.10.0 or higher

### ISSUE THREAD

**Issue by scherniavsky** [zalando-stups/documentation#67]
Would be nice if this could be documented in "Local Setup" and "Hello World" pages.

**Comment by hjacobs** [comment]
We are working on fixing https://github.com/zalando-stups/pierone/issues/65 --- let's hope to fix it before adding notes (and removing them afterwards) in the docs :smirk:

**Comment by outime** [comment]
It's been working for a while so I guess it can be closed.
