### ISSUE TITLE
Error in key encryption example

### ISSUE THREAD

**Issue by MALPI** [zalando-stups/documentation#69]
In the [Documentation](https://docs.stups.io/en/latest/user-guide/key-encryption.html) for key encryption your are giving the following example:
`
$ aws kms encrypt --key-id $KMS_KEY_ID --plaintext "<here-you-can-paste-your-pwd>"  --query CiphertextBlob --output text | base64 -D > /tmp/encrypted`

Which should be

`
$ aws kms encrypt --key-id $KMS_KEY_ID --plaintext "<here-you-can-paste-your-pwd>"  --query CiphertextBlob --output text | base64 -d > /tmp/encrypted`

See the **-d** flag.

**Comment by hjacobs** [comment]
Yes, for me it's "-d" too (Ubuntu) --- I guess it might be different on Mac?

**Comment by prayerslayer** [comment]
I'm on a Mac and it's uppercase `D` for me. We should add a note about this.

**Comment by MALPI** [comment]
Yeah, I am also using Ubuntu, actually I didn't know that there is a different syntax between Mac and Ubuntu.

**Comment by harti2006** [comment]
we could just write `--decode` which should work on both systems.
